
project_id = "dflvfgkqecwqpcfwkbqa"
[[secrets]]
name = "SITE_URL"
[[secrets]]
name = "GOOGLE_CLIENT_ID"
[[secrets]]
name = "GOOGLE_CLIENT_SECRET"
[[secrets]]
name = "SUPABASE_URL"
[[secrets]]
name = "SUPABASE_ANON_KEY"
[[secrets]]
name = "SUPABASE_SERVICE_ROLE_KEY"
[[secrets]]
name = "GEMINI_API_KEY"
